name: Beta Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Beta Release
    if: ${{ github.repository_owner == 'james-elicx' }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait for checks to pass
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'E2E Tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

      - name: Check out code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Set outputs
        id: hash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Alter version
        run: pnpm --filter itty-fs-router alter-version ${{ steps.hash.outputs.sha_short }} BETA

      - name: Build
        run: pnpm build

      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm --filter itty-fs-router publish --tag beta --no-git-checks
